{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "atlantis.serviceAccountName" . }}-role-bindings
subjects:
  - kind: ServiceAccount
    name: {{ template "atlantis.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ template "atlantis.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}